name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
jobs:
  release:
    name: Release - ${{ matrix.platform.target }}
    strategy:
      fail-fast: false
      matrix: 
        target: [x86_64-unknown-gnu, x86_64-unknown-musl]
        os: [ubuntu-latest, ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:   ${{ matrix.target }}
          override: true
      #- run: cargo build --release
