name: "Tag"

on:
  push:
    branches:
      - "release"

jobs:
  create-tag:
    name: "Create tag"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get tag"
        id: "get-tag"
        shell: "bash"
        run: |
          echo PKG_VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml) >> $GITHUB_OUTPUT

      - name: "Set Tag"
        shell: "bash"
        run: |
          echo "TEST" > aaaa.txt;
          ls;
          git tag -d v${{ steps.get-tag.outputs.PKG_VERSION }}
          result=$(git tag | grep "v${{ steps.get-tag.outputs.PKG_VERSION }}");
          ls;
          if [[ $result != "" ]];then 
            echo "已有标签";
          else
            echo "new tag";
            git tag v${{ steps.get-tag.outputs.PKG_VERSION }} && git push --tags
          fi